### ISSUE TITLE
Redirect `/prototypes` to `/prototype`

### ISSUE THREAD

**Issue by decentralion** [sourcecred/sourcecred#1019]
Consider the following url:

https://sourcecred.io/prototypes/sourcecred/sourcecred/

If you wanted to find other prototypes, it would be natural to truncate off the `sourcecred/sourcecred`, resulting in

https://sourcecred.io/prototypes

Unfortunately, this is a dead link. The correct link is: https://sourcecred.io/prototype

We can easily solve this by adding an internal redirect from `/prototypes` to `/prototype`. Likely we should copy from or extend [ExternalRedirect.js](https://github.com/sourcecred/sourcecred/blob/master/src/homepage/ExternalRedirect.js)

**Comment by wchargin** [comment]
Let’s rather redirect `/prototype/` to `/prototypes/`, yes?

As the name suggests, `ExternalRedirect` is not the right tool for the
job. You’ll want a new `InternalRedirect`. The server-side rendering
code will probably have to change a bit; see [the docs for `match`][1].

[1]: https://github.com/ReactTraining/react-router/blob/v3/docs/API.md#match-routes-location-history-options--cb

**Comment by expravit** [comment]
Why is `/prototypes/` even a route? 

I mean semantically - yes - `/prototypes/` infers that this route holds multiple items(plural) that one may be apt to check out. However we really only have one prototype we're dealing with(in this case, the application itself, not the instances/routes we've laoded into the app), don't we?

Why not disregard `/prototypes/` altogether and just use `/prototype/` for all of our various routing needs? Am I completely off-base with this, why not disregard the redirect and strictly use one route(both for landing on the prototype page, and for traversing the appended repo-entries) instead of using two routes that are more-or-less inconsistent with one another?

**Comment by wchargin** [comment]
@expravit: Yes, we should definitely pick either `prototype` or
`prototypes` and use that name consistently within all routes. I don’t
have a strong preference as to whether it should be singular or plural.
(Both are common, in my experience: this issue URL, for instance, is
`/issues/1019`, whereas pull requests are like `/pull/1025`.)

The discussion of a redirect is just for backward compatibility, to not
break existing permalinks that we’ve shared. But if we end up using the
singular form throughout then this might not be necessary, as we’ve
mostly told people to visit `/prototype/`.

**Comment by decentralion** [comment]
I don't think we've shared many links to /prototypes/, so I feel good about just deprecating the prototypes/ route as @expravit suggested, without setting up the redirect. Save the effort for things that will really matter to the project :+1:
