### ISSUE TITLE
PageRankTable UI: Linking Name and Cred Score 

### ISSUE THREAD

**Issue by BrianLitwin** [sourcecred/sourcecred#1041]
Wanted to mention that it's difficult to read the table given the distance between names on the left hand side and the cred scores on the right hand hand side. For example, when I view the screenshot below on my laptop, I'm really not sure whether my score is 2.78, 2.34, 1.59, or 1.17 without squinting at the table. 
<br> 

<img width="1246" alt="screenshot 2019-01-08 16 15 18" src="https://user-images.githubusercontent.com/26695477/50859204-bb334b80-1360-11e9-9712-f446461726d5.png">
<br> 
Probably not a showstopping issue for a Prototype, but would be good at have this on the radar.

**Comment by decentralion** [comment]
Good point, this is definitely a usability issue. I'd be happy to see solutions.

One classic approach would be to have alternating/shaded row highlights, although I worry that this will be ugly. Another solution could be to move the cred column to the left, so that the score is super tightly coupled to the description. Although having a score column then a description column would be a little intuitive, it would probably still be an improvement on the status quo.

**Comment by BrianLitwin** [comment]
What do you think about a cursor-hover effect? Could highlight name/cred, or the entire row.

**Comment by decentralion** [comment]
Sounds good to me! I like highlighting the entire row on hover.
