### ISSUE TITLE
Save Configuration Settings 

### ISSUE THREAD

**Issue by BrianLitwin** [sourcecred/sourcecred#1086]
Given the complexity of the config panel, it would be useful to be able to save your settings/combinations so that you don't have to remember them and re-build them from scratch when you're testing/experimenting with the settings.

**Comment by decentralion** [comment]
I agree. When we have Pagerank-on-the-Backend working, we'll also want to be able to use the config settings that were generated thru iterative front-end experimenting and save them to use as the canonical settings for backend runs on the project.

I'm thinking we should have have a download button in the weight config that downloads all the settings as a JSON file, and then you can upload them back to the weight config.

Also, we could have a button to persist the settings into local storage (or we could do that by default even). But having an explicit JSON file that the user manages is more general purpose+flexible because it admits using the settings in the backend too.

**Comment by wchargin** [comment]
This seems to be the opposite of #706. :-)

**Comment by decentralion** [comment]
Heh, yeah. Well, this is part of why I'd rather it be an explicit JSON file that the user is responsible for managing. In my experience local store tends to be a mess.

**Comment by Beanow** [comment]
Having the download/upload buttons + `--weights` parameter works fairly well imo.
Do you think we can close this?

**Comment by decentralion** [comment]
Yeah, I think we can close this since you can download weights.
