### ISSUE TITLE
Refresh timelines when re-running timeline cred

### ISSUE THREAD

**Issue by s-ben** [sourcecred/sourcecred#1206]
When I run SC using the `timeline-cred-development` branch (aka timeline cred), I can generate timeline graphs, such as this one for the Wasabi Wallet repo,
https://s-ben.github.io/wasabi-sourcecred-demo/site/timeline/zkSNACKs/WalletWasabi/

However, if I re-run SC, while it appears the database is updated, when I push those changes to my demo directory, the graph hosted on gh-pages does not change, even though it should show at least one new week of data. If I just create a new repo, I can see the new data,
https://s-ben.github.io/wasabi-sourcecred-demo2/site/timeline/zkSNACKs/WalletWasabi/

Not sure what's going on, and know this is still very much a beta feature, but just thought I'd bring it up.

This also makes me think of another potential issue: the best way to time-slice data. It appears that we're currently starting from the first commit (sensible), then calculating in weekly intervals forward in time (again makes sense), but then stopping at the last full week interval, which truncates any contributions made since the last full week. This is what happened in my most recent example, which ends with data for the "Week of June 30", even though it's July 7th and it would be nice to see the most recent data.

This is essentially a signal processing problem, as mentioned in office hours by (who was it, so I might give him cred??). In traditional signal processing, this is the 'windowing' problem. Since the data being transformed rarely exactly fits the window size, you have to somehow handle the data that falls outside the window at the beginning or the end (whichever you cut off). In timeline cred, actually the most up-to-date, "real-time" information will be most interesting for many cases. We definitely don't want to cut off the last week. So "chopping off" at the beginning makes more sense. And by chopping off I don't mean deleting, but just merging that data with the first full window, or "zero padding" the leftover days and pretending those contributions were made in a full week instead of just a few days. 

Hope I'm not rambling here. Can break up into smaller issues if need be.

**Comment by decentralion** [comment]
> However, if I re-run SC, while it appears the database is updated, when I push those changes to my demo directory, the graph hosted on gh-pages does not change, even though it should show at least one new week of data. If I just create a new repo, I can see the new data,

I speculate that this might be caused by #987. Basically, the way the GitHub updater is setup right now, if you update less than a week after the last real load, it won't actually get new pull requests, etc, from GitHub. It could be that you ran the update before a week, and it wasn't working, and then you created the 2nd repo after the one week mark, so it updated correctly. However, it might be that I'm wrong and there's something more subtle going on. As a workaround for #987, I can change the GitHub TTL to change the TTL to 1 day instead of one week. If this issue keeps coming up, we can dig into it more. 

> stopping at the last full week interval, which truncates any contributions made since the last full week

Yeah, this is a bug in the version of timeline cred you're using. The productionized version (#1212) has testing, and I caught and fixed that bug in testing. :)

**Comment by decentralion** [comment]
I'm hopeful that #1214 will address the first issue described here. @s-ben, if it keeps happening feel free to re-open this (ideally with a specific repro).
