### ISSUE TITLE
Plugin generalization through booture?

### ISSUE THREAD

**Issue by Beanow** [sourcecred/sourcecred#1425]
In the past I've used https://github.com/fluture-js/booture as a way to declare dependencies in an application and do parallel acquiring and disposing of them.

Something very similar could be done to have a flexible yet declarative dependency structure between plugins.

The GitHub plugin exposes:
- `github-data` access to the (updated) mirror
- `github-references` a reference detection service
- `github-graph` the updated graph

The Discourse plugin exposes:
- `discourse-data`
- `discourse-references`
- `discourse-graph`

Core components:
- `references` depends on github and discourse reference detection services.

The initiates plugin:
- `initiatives-graph` depends on `references` and `discourse-data`.

The identities plugin:
- `identities-graph` which depends on the other graphs and provides the collapsed version

This still requires some hand-crafted dependency structure, however I think it is a great way to make the dependency DAG visible, generalize execution ordering and parallelism.

I would be able to provide some more concrete code examples / champion such a refactor.
But more to the point, I want to know what your opinions are on:

- Using a service locator style declaration of plugin components.
- Using a general purpose middleware-like system to handle parallel loading of this.

**Comment by Beanow** [comment]
cc @decentralion @wchargin

**Comment by decentralion** [comment]
I'm not sufficiently familiar with booture, or the service locator design to have any feedback without doing a bunch of research into this. Since I'm focused on other goals right now, I'm going to punt on doing the research I'd need to do to offer feedback. 

From a roadmap / prioritization standpoint, I'm thinking the following are all higher priority than improving the plugin system:
- Setting up initiatives/artifacts and getting retroactive coverage within SourceCred
- Using initiatives/artifacts to get better visibility into the "why" of people's cred
- Making better infrastructure for deploying cred instances and updating Grain, and making it possible to onboard other users

Only after those 3 are handled do I think we should really invest energy into rebuilding the plugin system. (Although I'm happy for you to keep thinking about it and posting your ideas between now and then--I'm just not likely to invest a lot of effort myself until we've gotten the higher priority tasks handled.)

**Comment by Beanow** [comment]
Agreed on punting this for now. Wrote this down with the idea of revisiting it once a plugin revision is due.

A TL;DR on the service locator pattern, it's a pattern where you have a central registry of implementations and use a highly abstract lookup in this registry to depend on these implementations. (In this case, by a string identifier)

It allows for very flexible, run-time dependency injection. In this case booture will create a DAG for us and resolve the dependencies in the correct order and even in parallel when possible.

**Comment by Beanow** [comment]
I think this isn't enough of a priority right now to keep this issue open. Let's revisit when it's a more appropriate time.
