### ISSUE TITLE
Target node v13

### ISSUE THREAD

**Issue by Beanow** [sourcecred/sourcecred#1485]
Performance improvements, experimental [WASI](https://github.com/bytecodealliance/wasmtime/blob/master/docs/WASI-intro.md) support and more cool stuff landing in v13 of Node.
:rocket: https://nodejs.org/en/about/releases/ :star2: 

That said, v13 will not be here for long. It's not going to be a LTS version. With v14 taking up that role around next summer.
![image](https://user-images.githubusercontent.com/497556/70436684-29f5b900-1a8a-11ea-9784-202c02c6f080.png)

For a while, we've been targeting v12 and v10. This was during the period where v12 was the current version. i.e. it will have new features landing, not being in maintenance mode. So the current setup had us developing in and shipping docker images with the current release (v12). While ensuring v10 compatibility through the test suite.

Honestly I don't see a reason why this wouldn't work for:
- Developing and shipping with v13.
- Testing against v10 and v12 as LTS targets.

And particularly when we're ready to frequently ship NPM packages, the extended coverage will be really useful.

So I'm proposing we switch to v13 as our main target, and support v10 and v12 through tests.

**Comment by nothingismagick** [comment]
I dunno - the odd numbers of node are generally considered to be unstable and I would never use one unless I am actively working on node. I think its kind of weird that they are using 13 for such a short time and that is a signal to me that they are going to be using it for staging for 14. Especially because there are really massive issues with imports / requires now needing to be named etc.

I think it makes more sense to wait 4 months and target 14 then.

**Comment by Beanow** [comment]
So, with not a whole lot of time before v14 becomes a thing. Let's close this.
