### ISSUE TITLE
remove un-used line from graph.js

### ISSUE THREAD

**Issue by vsoch** [sourcecred/sourcecred#1598]
Hey friend! We've discovered a line that is no longer used, but still included in the code base:

https://github.com/sourcecred/sourcecred/blob/74acd1fa80a631ea34f98b685e2e2dc77fa75db7/src/core/graph.js#L267

And see discussion after the line (and below) about this. But never fear! We have morphed this into a good first issue for a new contributor. Here is how you can go about fixing this issue. The steps below are general, and please ask for help (here or another platform for sourcecred) if you need it!

## Working on Code
1. **Create a GitHub account**: If you haven't yet, sign up for GitHub. This usually means creating a username and then providing an email. You can have some fun by adding a profile picture, and checking out other customizations in your user profile under "Settings."
1. **Fork the repository**: If you look at the main [sourcecred/sourcecred](https://github.com/sourcecred/sourcecred/) repository (or the upper right here) you'll see a "Fork" button. Nope, no spoons here, click that button and select your user account to fork it, or create a clone of it to your account.
1. **Clone your fork**: You next want to get the repository onto your local machine. You'll need to install git and then esentially do `git clone git@github.com:<username>/sourcecred` If you don't use ssl, you'll just do `git clone https://github.com/<username>/sourcecred`.
1. cd into sourcecred, and check out a new branch, `git checkout -b fix/unused-graph-line` (or call something better).
1. Open the file, it's under core/graph.js and remove the line that we showed above. 
1. Commit your changes with a meaningful message! `git commit -a -m "Removing unused line in graph.js to close #1598"`
1. Push to your branch, typically `git push origin fix/unused-graph-line`

## Open Pull Request
Then you can navigate to your repository page, click on Pull Requests, and open the pull request! You want it to be your branch (of your fork) against the master here. 

1. Click the button to open the pull request, selecting the correct branch
1. Write a description in the box for what you are changing, and what issues (this one!) you are addressing. Note that if you say anything along the lines of "fixes #1111111" or "closes #111111111" it will automatically close the issues when you merge (neat!)
1. Extra points! If you write a small story or poem about the lonely line 267. Art would be fun too :)
1. Ping others in the discord #needs-review channel 

And that should be it! The above should be relatively fun, and a good learning experience for forking, cloning, changing, committing, and opening a pull request. And guess what, there are definitely more advanced stuffs you can do with git, but that's largely the basics that will empower you to contribute to most projects!

- - -
We check for all cases (equal, less, greater than) and for the first we return, the other two we throw errors. What circumstances would lead to getting to the last statement?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200032326400385/1200038439361785) by [Unito](https://www.unito.io/learn-more)

**Comment by decentralion** [comment]
I think we never reach that last statement. Looking at the [git blame](https://github.com/sourcecred/sourcecred/blame/74acd1fa80a631ea34f98b685e2e2dc77fa75db7/src/core/graph.js#L267), it looks like that line was added in a different commit from the immediately pre-ceding code. So it's likely a bit of redundant logic that slipped in by accident.

**Comment by vsoch** [comment]
That happens sometimes with git, and there really is no harm done in this case. Albeit, maybe that little function has gotten quite lonely sitting there, poor little guy.

**Comment by vsoch** [comment]
oh! You know this would be a super opportunity for someone new to GitHub to open a pull request with this change - just to delete that line! Maybe we can discuss on Tuesday.

**Comment by wchargin** [comment]
This was included to ensure that every return point (`return`, `yield`,
or implicit return) had a comodification check. It’s true that it
shouldn’t actually be reachable in normal code, though it technically is
reachable if a client passes a value of `since` that defines a `valueOf`
property that is not pure. But it’s easier to see at a glance that all
potential return points are in fact checked if we just keep this in, and
in particular it is possible to do so mechanically.

That said, I don’t feel strongly about keeping it (feel free to remove
it if there’s a good reason), but I don’t think that this is necessarily
a good first issue. We try to reserve that label for tasks that both are
accessible to new contributors _and will help them ramp up to the
system_ (rather than just being grunt work). Deleting an unused line of
code doesn’t really meet the second criterion, imho.

(Regardless, editing issue title to remove prefix that’s redundant with
label.)

**Comment by wchargin** [comment]
> Looking at the [git blame][1], it looks like that line was added in a
> different commit from the immediately pre-ceding code. So it's likely
> a bit of redundant logic that slipped in by accident.

…but that commit was specifically called “Check graph invariants during
tests”, so no, it wasn’t accidental.

[1]: https://github.com/sourcecred/sourcecred/blame/74acd1fa80a631ea34f98b685e2e2dc77fa75db7/src/core/graph.js#L267

**Comment by vsoch** [comment]
I think it’s a good first issue not for someone contributing to sourcecred, but someone entirely new to GitHub that happens to be in the sourcecred community. The fix is straightforward, and it lets the contributor focus on the interactions with git and the GitHub flow. Being on here for many years it’s easy to forget what learning this is like for someone who hasn’t done it before.

**Comment by wchargin** [comment]
It’s great that we want to encourage non-technical contributors to
contribute to those areas where they have something to add—which might
include docs, organization, art, or more. We should focus our onboarding
efforts on those areas rather than this code repository.

In a code repository, there’s a higher barrier to entry. You need `npm`
or `yarn` installed—and, as you might advise, preferably in a Docker
container or other jail. You need to know how to run type-checkers,
linters, and tests. You might need to configure GitHub API keys. Even at
the most basic level, you need to be comfortable with an editor that’s
suitable for code, whereas non-technical contributors might be happier
with a dedicated Markdown editor (with live preview) plus graphical Git
client (or just the GitHub web UI). This is all baggage that will
confound people who aren’t familiar with this ecosystem, especially if
the change itself is not meaningful to them (what does “unreachable”
mean, and what does deleting this line even do?).

If we focus our efforts on (e.g.) helping people who want to contribute
to docs do so effectively, then the interactions can be genuine and
tightly motivated every step of the way. We won’t have to encourage
people to write a small story or poem or piece of art about a deleted
line of code (which doesn’t really communicate the purpose of this
repository, the change, or our conventions), because they’ll be closer
to their comfort zone already.

So I’ll propose removing the “good first issue” label here, and
encourage you—if this issue is important to you—to maybe consider
documenting the [`sourcecred/docs` repo][docs] (itself scarcely
documented!) to link to some existing tutorials about contributing on
GitHub from a non-technical perspective, or write such material yourself
if you find in your search that the existing resources are inadequate.
We’ll also have some good opportunities at CredCon to discuss this in
person and get some feedback from Real Live Non-technical People.
What do you think?

[docs]: https://github.com/sourcecred/docs

**Comment by vsoch** [comment]
I disagree that there isn’t a learning experience here that would be valuable without needing to install Docker or npm, and of course I agree that the docs repository is going to be great! I’m purposefully adding one main community file at a time and giving folks ample time for feedback so it’s done without rushing or pressure. After the community docs I’d be more than happy to, in addition to this issue, write something more official up.

**Comment by BrianLitwin** [comment]
@vsoch Another strategy to try to ramp up new contributors in this repo is to look at the code comments/docs for grammar/spelling mistakes or inconsistencies. E.g. [this line](https://github.com/sourcecred/sourcecred/blob/3d3c8c92b3129803e851dd31645954cac250bbc6/src/graphql/mirror.js#L1030) should have an "a" verse an "an" at the end.

**Comment by AL0YSI0US** [comment]
![Screenshot_20210331-012455.png](https://user-images.githubusercontent.com/75811965/113114445-342c5100-91c0-11eb-99d5-287bd3df3c2b.png)

👋🏾 Newcomer here, and I'll bite with some questions...

**Current Status**
1. Is this still an issue that needs to be resolved as initially requested? 

**Clarification**
2. Is the line to be removed the function on line 267 which is also clled again on line 278 

````javascript
this._maybeCheckVariants();
````

3. Would this issue be resolved by pulling one (267) or both (267, 268) of these functions and ensuring there are no syntax errors afterwards?
