### ISSUE TITLE
Improve the "Ledger Admin" page

### ISSUE THREAD

**Issue by decentralion** [sourcecred/sourcecred#2172]
As discussed on a call with @befitsandpiper:

- Currently UI is hard to use and navigate, confusing that the update pane is at the bottom after all identities
- Suggest putting identities into a fixed-size scrollable pane so update pane is always visible
- Then add a search to filter down identities

**Comment by topocount** [comment]
some thoughts to help shape this a bit more:
- search filter should be a combo box
  - combobox should populate with the identity selected from the scrollable pain
- scrollable pane should be on either side of the main view, kind of like a menu list. I think the right side makes sense, to balance out the view menu on the left but I can easily be convinced otherwise

**Comment by blueridger** [comment]
duplicate
https://github.com/sourcecred/sourcecred/issues/2490
