### ISSUE TITLE
GitHub plugin load should not die due to rate limit

### ISSUE THREAD

**Issue by decentralion** [sourcecred/sourcecred#2201]
When we're loading the GitHub plugin, it currently dies when the API rate limit is exceeded. When the user is working with a local cache, this is OK because they can wait an hour and re-try. However, when this is happening on a GitHub action, it would be far better if the job would simply wait an hour and then continue loading, so that it would eventually succeed (and save all the data in cache).

I believe we should add the wait/and/retry logic here:
https://github.com/sourcecred/sourcecred/blob/cd92a24ba1456163040124868a5d9944dcf9d4b8/src/plugins/github/fetchGithubRepo.js#L263-L268

**Comment by befitsandpiper** [comment]
So... it seems like we can set retry for the github rate limit issue to true, and set a timeout for 1 hour to not run into rate limiting again right away. But then doesn't the github action start again from the beginning? How do we save the progress and continue from where we left off rather than resetting?
