### ISSUE TITLE
Allow grain UI to show more than 2 digits past the decimal

### ISSUE THREAD

**Issue by befitsandpiper** [sourcecred/sourcecred#2778]
1hive is starting to move minimum distribution sizes close to the lower end of hat the UI shows bc of the recent HNY price increases. It would be nice if the number of decimals shown was configurable.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200032326400385/1200038301242225) by [Unito](https://www.unito.io/learn-more)

**Comment by topocount** [comment]
I think this might be an issue with the grain format function, but it is a pretty subjective concern:
https://github.com/sourcecred/sourcecred/blob/aa1a46943d83da3f61bbfae797021976e08d1240/src/core/ledger/grain.js#L146-L147

The question is, what is the expected behavior when the total amount to render is smaller than the decimal total? At what point do we switch to scientific notation? should we introduce some notion of significant figures into this function to ensure we don't have absurdly long number strings showing in our frontend?

ETH has special names for different orders of magnitude of ETH: https://github.com/ethereumjs/ethereumjs-units. Would you want to develop unit names for different orders of magnitude of Honey?

I think a more sustainable solution is [SI unit prefixes](https://en.wikipedia.org/wiki/Metric_prefix). Would that work for the folks at 1Hive? It'd also probably help to have a tooltip that shows the raw decimal as well.

**Comment by decentralion** [comment]
Note: The format function already supports customizing the number of decimals:

https://github.com/sourcecred/sourcecred/blob/aa1a46943d83da3f61bbfae797021976e08d1240/src/core/ledger/grain.js#L103-L107

We could just update the currencyConfig file to admit a custom decimal precision:
https://github.com/sourcecred/sourcecred/blob/aa1a46943d83da3f61bbfae797021976e08d1240/src/api/currencyConfig.js
