### ISSUE TITLE
Design core data models

### ISSUE THREAD

**Issue by wchargin** [sourcecred/sourcecred#29]
Let’s use this space to design the core data models for SourceCred. Following is a brain-dump of the current state of affairs as of 2018-02-22-ish, as developed in conversations between @dandelionmane and myself.

## First attempt: the project DAG

Originally, we considered the following scheme.

The _project graph_ is a DAG whose nodes are primarily _contributions_: contributions include commits, pull requests, issues, comments on PRs and issues, design docs, etc. A weighted edge from *a* to *b* indicates that *b* provided value to *a* (in proportion to the edge weight). The leaf nodes of the graph correspond to users. There is only one instance of this graph, which serves as a reflection of the repository’s “official”/“objective” value function. Individuals can update the graph by standard pull requests (and maybe also via some lower-friction, continuous workflows; details to be fleshed out).

There is a root node in the graph representing the repository as a whole. The graph will likely also include “subprojects”, which may be functional areas of the application (“frontend”, “backend”, “plugins”), organizational divisions (“buildcop”, “triage”), or anything else that is perceived as important to the organization.

At allocation time, one unit of cred is minted to the root node. The cred “flows down” the graph, roughly according to the following algorithm. Let *n* be a node all of whose parents have been visited, and let *c* be the amount of cred that has flowed to *n*; then, to each child *n*′ of *n* with normalized edge-weight *p*, flow *p*&nbsp;*c* cred to *n*′. Repeat until all nodes have been visited. Each user receives cred proportional to the amount of cred at their respective leaf node.

One particularly desirable property of this mechanism is that it is _transparent_ in the following sense. Suppose that we want to understand the distribution of impact among users for some subcomponent of the project: e.g., we want to see who has contributed the most value to the backend APIs. We can rerun the algorithm on the same project graph, but mint 1¤ to the “backend APIs” node instead of the root project node. The results will be useful because the process is _additive_. For instance, if a project has a root node with two children—“backend”, with weight 0.6; and “frontend”, with weight 0.4—then a user’s cred will be _c_<sub>total</sub> = 0.6 · _c_<sub>backend</sub> + 0.4 · _c_<sub>frontend</sub>, where _c_<sub>_u_</sub> is the credit assigned to the user when the search starts from node _u_.

## Second attempt: the project graph

A major problem with this approach is the requirement that the graph be acyclic. We expect cyclic project graphs to be quite common in reality. (TODO: Provide examples.) In such cases, the process described above no longer directly applies. Instead, we would like to continue flowing cred along edges until we reach some kind of equilibrium.

Note that if we interpret a project DAG as a Markov chain, then the process described above can also be formulated as, “find the distribution of the chain after a large number of steps when starting from a distribution that is at the root node with probability 1”. Markov chains generalize to graphs with cycles, so we will attempt to formulate an improved version of the system along these lines. An immediate problem is that the chain is not likely to be ergodic—users will be leaf nodes, so will not communicate with other states—so we will have to be careful when dealing with limiting and stationary distributions.

A natural first idea is to simply take the limit distribution *π*₀ *A*<sup>*k*</sup> for large *k*, where *π*₀ is the distribution that has 1 for the root node and 0 elsewhere. Then, we could restrict the support of the resulting distribution to the nodes corresponding to users, and after normalization we would have a valid allocation. While this seems reasonable so far, it is not clear how to achieve the transparency discussed above. The strategy of “assign 1¤ to an arbitrary project node and re-run as normal” does not obviously do the right thing: if the chain is ergodic, then changing the initial conditions does not affect the limiting distribution, and a densely connected graph may be “nearly ergodic” enough for the cred to become “all mixed up”. (As you might guess from reading this paragraph, the precise dynamics of what goes right and wrong, and how, are not clear to me. It might be helpful to run a simple version of these algorithms on some toy repos and some real-world repos to explore the behavior.)

More info to be posted in this thread.

**Comment by Recmo** [comment]
(@dandelionmane introduced me to this problem yesterday).

Can you explain how the transparency criteria works in the case of a DAG that is not a tree? Let's say frontend and backend have some overlap in submodules:

```
    +-->frontend +---------+
    |        +             |
    +        |             |
root         +---->shared +-> user
    +        |             |
    |        +             |
    +-> backend +----------+
```

**Comment by dandelionmane** [comment]
In the past, we were expecting to have relatively hard barriers between different projects. Each project would issue its own cred, which would be a distinct exchangeable cryptoasset; within this view, it made sense to start with a top-down view that begins at the project root and progresses down to subprojects, and then directly to contributions. 

Now, I'm thinking of SourceCred as more of a "web-of-contributions", in which the underlying data structure is just a directed graph. There are three kinds of nodes: *projects*, *contributions*, and *identities*. 

A *project* is an attempt to make an easy entry point for recognizing the value provided by a set of contributions. It has directed edges (or, transitively, paths) to all of the contributions that compose the project. For example, I expect `SourceCred`, `SourceCred/explorer`, and `SourceCred/explorer/infrastructure` to all be projects. `/infrastructure` would have edges to the PRs that set up frontend infrastructure, like #22 and #27. `explorer/` would have edges to `explorer/infrastructure`, and so forth. 

A *contribution* is something that adds value to the project. It's a deliberately broad concept; in the case of SourceCred, I expect pull requests, issues, issue comments, Git commits, and giving talks could all be contributions. Contributions have edges to things they depend on. For example, let's consider #27. I imagine it having edges to:
- The two PRs that it directly references, which are the actual bugfixes we want merged
- @wchargin, for merging the PR
- @dandelionmane, for reviewing and merging the PR
- the SourceCred/infrastructure project, since it builds on the rest of the infrastructure in the SC frontend, and wouldn't have any value absent that context

As a consequence of those edges, it will likely also have paths to:
- babel-plugin-flow-react, because it points to two PRs in that project
- flow, via babel-plugin-flow-react
- react, as above
- babel, as above
- itself, via SourceCred/infrastructure (cycles will be *very* common)

Also, I think SourceCred/infrastructure should point to SourceCred/ root, because SourceCred frontend infrastructure derives its value from being useful to SourceCred as a whole, and if someone else e.g. makes a massive contribution to the SourceCred backend infrastructure, it makes the SC frontend infra more valuable as well.

Also, I think another path from #27 to SC/root would be via the PRs in babel-plugin-flow-react, e.g. https://github.com/brigand/babel-plugin-flow-react-proptypes/pull/182. That PR, which provides value to b-p-f-r, exists because the SourceCred project decided to use b-p-f-r, and people primarily focused on SC went and fixed it for them. So I think there's a real sense in which the SC project (or maybe more immediately: sc/explorer/infra) has contributed value to babel-plugin-flow-react.

Moving on: an *identity* is an agent or actor that deserves cred for contributing value. Identities can have edges to other identities, projects, and contributions; for example, it might make sense to create a "team identity" that has edges to the members of the team; this might be a good way to capture the value of e.g. managers, who don't directly create many recognizable contributions but let a group of people work more effectively. Also, identities may want to recognize that they derive value from other projects; for example, if I use Ubuntu and XMonad, I may want to flow value to those two projects.

(Aside: I think in the future we'll want "scoped identities" that are scoped to projects or other contexts. Hypothetically, when I make a contribution to sc/explorer/infra, by default I want to flow value to a vim-react plugin, but when I make a contribution to sc/design/incentives, I want to flow value to the authors of an open-source game theory textbook. These are future considerations.)

This graph gets weird in a recursive way when you consider that the graph, itself, is a contribution. For example, if I do a bunch of housekeeping work on the SourceCred/Explorer project (e.g. I discover a lot of important contributions that weren't acknowledged by the project, but according to our practices on maintaining the top level projects, they should have been), then that modification to the cred graph is itself a contribution that merits some cred. I'm not sure how to model that, exactly.

Question: Does this seem like a good semantic fit for the task of attributing credit to projects? Do you agree with the examples in the case of SourceCred?

**Comment by dandelionmane** [comment]
If we provisionally accept the data model I described above: I think it's helpful to next explore what kinds of questions we want to answer. I think we want to assess the value provided by a {project, contribution, identity} in a way that is consistent across different contexts. Here are some examples questions within this framework:

- How valuable is the React project, in general? (~ Relative to all other projects globally, how valuable is React?)
- How valuable is the React project to SourceCred? (~ Relative to all other projects or dependencies, how much value did React contribute?)
- How valuable was #22 to the SourceCred project? How does its value compare to #21?
- How much value has @dandelionmane contributed to open-source projects in general? How much have they contributed to SourceCred? How much have they contributed in the context of frontend projects across the ecosystem? (Is there a way to define a meta "frontend-project" which can be used to measure generic "frontend-cred", as abstracted across individual projects?)

I think we need a function that takes a set of nodes that we want to value (e.g. the set of all projects and contributions that constitute React) and a set of nodes that is the scope for evaluation (e.g. the set of all projects and contributions that constitute SourceCred), and the function returns a scalar value. I.e. 

`C :: Set(Node) -> Set(Node) -> Number`

I think `C` should have the following properties:
- The amount of cred attributed to a set of contributions should be the sum of the cred attributed to the contributions within that set, after accounting for duplication. Formally, if `A` and `B` are sets of contributions and `ω` is an arbitrary context, then:
If `A∪B=U` and `A∩B=I` then `C(A,ω) + C(B,ω) - C(Y,ω) = C(X,ω)`

- The amount of cred attributed to a set of contributions across all contexts should be equal to the sum of the cred attributed to those contributions in every particular context, after accounting for duplication. Formally, if `A` and `B` are sets of contributions acting as a context, and `ω` is an arbitrary set of contributions being valued, then:
If `A∪B=U` and `A∩B=I` then `C(ω,A) + C(ω,B) - C(ω,I) = C(ω,U)`.

I believe these properties include the transparency result, in that when we look at the cred attributed to any node, we can meaningfully decompose that cred into the contexts that originated it - e.g. someone's cred in X project may be the sum of their cred in X/backend and X/frontend.

A few other properties we will want:

- Resistant to gaming by projects, e.g. the total cred allocated to SourceCred should not be meaningfully modifiable by SourceCred adding or removing internal edges. (Need some more thought to formalize this.)

- Respects graph transitivity, e.g. if `X` is a high cred node, and `X` has a high weight edge to `Y` and few other edges, then `Y` should be a reasonably high cred node.

Also, trivially:
`C(∅,X) = 0` and `C(X, ∅) = 0`.

**Comment by decentralion** [comment]
The core data models are sufficiently designed, such that we don't need this issue to be open.
