### ISSUE TITLE
[Identity] Defining the service contract

### ISSUE THREAD

**Issue by blueridger** [sourcecred/sourcecred#2976]
What is the service contract (api interface) between the client and the `/mergeAccounts` lambda endpoint?

**Comment by hammadj** [comment]
The payload for the mergeAccounts endpoint would be empty since the only information we need is given in the Auth headers (e.g. https://github.com/MetaFam/TheGame/blob/master/packages/utils/src/did/index.ts)

Updated the original issue to clarify: https://github.com/sourcecred/sourcecred/issues/2853

**Comment by blueridger** [comment]
Um.. Could you be more explicit? Like give an example HTTP request showing the header structure?

**Comment by hammadj** [comment]
Sure, here's some rough code:

Function to generate auth token:
```ts
async function createToken(provider: Web3Provider): Promise<string> {
  const signer = provider.getSigner();
  const address = await signer.getAddress();

  const claim = JSON.stringify({
    iat: +new Date(),
    iss: address,
    aud: 'sourcecred',
    tid: uuidv4(),
  });

  const proof = await getUserSignature(provider, claim); // Signature from Web3 provider

  return Base64.encode(JSON.stringify([proof, claim]));
}
```

Auth token usage when calling `/mergeAccounts` endpoint:

```ts
const token = await createToken(provider);

fetch(`${API_ENDPOINT}/mergeAccounts`, {
   method: 'POST',
   headers: {
    'Authorization': `Bearer ${token}`,
  },
});
```
