### ISSUE TITLE
Investigate nondeterministic GitHub query rejections

### ISSUE THREAD

**Issue by wchargin** [sourcecred/sourcecred#350]
In #349, we saw what appeared to be a bug in continuation resolution
when run on `ipfs/go-ipfs`:

```
TypeError: Cannot read property '_n0' of undefined
    at embeddings.reduce (/home/wchargin/git/sourcecred/bin/commands/plugin-graph.js:442:153)
    at Array.reduce (<anonymous>)
    at resolveContinuations (/home/wchargin/git/sourcecred/bin/commands/plugin-graph.js:442:82)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

I’ve investigated this. It is not a bug in our code, per se. What is
happening is the following. Sometimes, when we post a query to the
GitHub GraphQL API, the response is (prettified):

```
{
  "documentation_url": "https://developer.github.com/v3/#abuse-rate-limits",
  "message": "You have triggered an abuse detection mechanism. Please wait a few minutes before you try again."
}
```

Note that this links to the v3 API, even though we’re using the v4 API.
Also note that we are not using the API to rapidly create content,
polling (at all), or making multiple concurent requests, and it seems
surprising that the data that we are requesting should be
computationally expensive (e.g., we are not forcing computation of Git
diffs; we’re just fetching standard fields off the standard objects).

First of all, this is not a [valid GraphQL response][1], so it is not
surprising that we do not have logic to handle it.

[1]: https://facebook.github.io/graphql/October2016/#sec-Response-Format

Second, whether this error is produced appears to be nondeterministic.
Running the same sequence of queries multiple times can lead to exactly
the same results (failures and all), or it can be the case that the
first sequence fails and the second succeeds. One potential explanation
for this is that the abuse detection depends on actual compute resources
used by GitHub’s servers, and so initial queries cause the caches to be
hot for the particular resources in question. Or, it could just be a
fluke.

We should probably, nevertheless, attempt to fix this. For instance, we
could detect this error and, as the message suggests, wait some time
before re-issuing the query.

**Comment by wchargin** [comment]
Useful debugging/investigation tool: https://gist.github.com/wchargin/a6336f5730d0d09a25562b83120d1a95

**Comment by decentralion** [comment]
I think this is the actual error @mikeal was telling me about. It's confusing that GitHub apparently has two different ways to die on large GraphQL requests: either the "unknown error (possibly timeout)" that we were seeing prior to https://github.com/sourcecred/sourcecred/pull/349, or this failure.

I think the situation here would be substantially improved if we cache the GitHub response (inc. continuation queries) to disk as it's generated. That would have two consequences:

1. On the user's first request to a large repo, it may fail. However, since they will have cached a bunch of data received prior to triggering this mechanism, they will still have made progress. Running the program a few more times will eventually get them into a good state. This is much better than the status quo, where if it doesn't Just Work you're pretty much stuck.
2. Once they're in a good state, subsequent runs will just pick up new activity via the continuation query, which will result in much better performance, less stress on GitHub, and will avoid this failure

**Comment by mikeal** [comment]
Sometimes the status/headers will even call it a rate limit error, but it's at the gateway level and isn't documented or part of your "rate limit" that is exposed by the API.

**Comment by wchargin** [comment]
@decentralion: Here are my thoughts on your proposal.

First of all: I like it. It seems like clearly a good thing to do.

Second: it seems that this kind of data (partial results and
continuations) should be stored in a plugin-specific data directory, so
we’ll want some simple abstraction for that.

Third: I note that the proposal assumes that the queries will fetch a
consistent state of the repository over multiple requests. This is of
course not true in general. Now, this assumption is already present in
the current version of the code, basically by necessity: we can’t
instruct GitHub to commit a DB snapshot, for obvious reasons, so this is
just another design constraint that we have to consider. But the model
described in your point (2) greatly increases the strength of the
assumption: we’re assuming that results from a repository are
conservative extensions of not just “very recent” results but also
results at arbitrary times in the past. This changes the game from “if
your queries are fast enough and your repository isn’t being touched
every second, you’re probably okay” to “sooner or later, someone _will_
delete a comment in the repository (or make some other incompatible
change), at which point you’re out of luck”. This may motivate us to
devise some intermediate format that is robust to such modifications.
For instance, currently the continuation queries have associated
structures like, “run this continuation, then merge it into element 17
of `results.repository.issues.nodes`” or whatever. Replacing indexing
with some more stable content address (issue number, unique pull request
review ID, etc.) could improve robustness.

Fourth: there are two degrees to which we could implement the proposal,
which vary in difficulty. Implementing point (1) of your list is
reasonably tractable: once we have the plugin-specific data directory
working, this change should probably be about a day’s work. But your
point (2) is a bit harder. Currently, when a query returns with
`hasNextPage: false`, we consume the relevant continuation, because we
have found all relevant data. The model that you propose requires
keeping around these continuations and querying them again when we want
to check for updates to the graph. This is certainly possible, but will
take some doing—especially if we want to be robust to long-term
backward-incompatible changes, as described above.

Finally, and related only indirectly to this conversation: as we make
the GraphQL logic more complex, we may want to keep in mind the option
of autogenerating Flow types from the GraphQL schema.

**Comment by mikeal** [comment]
One thing you may also want to consider in the future if you're trying to pull in more data across GitHub: starting with a graph populated by continual updates from gharchive https://www.gharchive.org/

If you already know all the issues and base level information and just need to get comments or other leaf data out of GraphQL there's some tricks you can do with the search API to run those sub-queries across 100 specific issues or repos or people all at once by creating a large search string with each one.

**Comment by decentralion** [comment]
### Plugin Specific Directories

I agree; the `Git` plugin would benefit even more from caching its
results than the GitHub plugin does. (I believe we would not have
consistency issues?)

### Consistency issues

In the long term, if this system is to be decentralized, we can't avoid
thinking about consistency issues. Within individual scopes it's
possible to maintain consistency; across scopes (e.g. plugin boundaries)
it's much harder. 

It would be interesting to have a design discussion about how to handle
consistency problems in general. The space of possible
solutions is very large; for example, making a blockchain would be one
way to do it. But that would introduce enormous complexity which is
incidental to SourceCred's present goals, so: let's not :)

The core algorithms will need to be accommodating of cases where
consistency has been violated. I think we can do this in a generalizable
way by handling all reconciliation when merging graphs, so that any
graph can be considered internally consistent. Then we can provide
scoped resolvers that can use plugin-specific logic to accommodate their
own inconsistencies.

As other plugins begin interacting more richly with the GitHub plugin,
we'll need to solve consistency for the GitHub plugin. But for now, we
_could_ punt on it.

I would really like if we can get to a solution that is robust, even if
not fully correct. That is, when underlying consistency is violated, it
may show locally corrupted / inconsistent data, but the data still
loads, displays the same UI, approximately the same PageRank. 

Then we can implement the GitHub plugin caching with a ~24 hour TTL,
which I think will minimize the rate of consistency problems, and also
make the software feel far more performant. 

Alternatively: we can implement the caching purely at the CLI layer;
rather than getting true incremental querying, we could just cache the
result of `sourcecred graph foo bar` with a 24hr TTL. I guess this would
manifest similar performance benefits with a fraction of the
implementation complexity. Then we can focus instead on actually
developing credit attribution. :)

### Autogenerating flow types for GraphQL

I think this is pretty low priority. The manual process seems fine to
me. We're unlikely to merge many bugs because Flow will complain at type
usage even if it wasn't added properly at source. And at our current
rate of GraphQL query modification, the labor savings from automating it
will not be significant.

**Comment by decentralion** [comment]
@mikeal the important thing to us with the GitHub API is that it's possible to query just for an individual repository or organization's data in an efficient fashion. That makes it feasible to not have any central SourceCred servers, and instead have all the users get their own copy of the data from GitHub (in the future, from IPFS). It seems to me that the gh-archive won't be very useful in this model, because individual users won't want to download the whole history of GitHub in order to analyze the particular project they're participating in.

**Comment by mikeal** [comment]
@decentralion totally makes sense. Just FYI, at some point we'll have a processing pipeline that converts the information in gharchive into IPFS. This would allow individual nodes to subscribe to information about specific repos or orgs in the future and could see your data needs without dealing with GitHub rate limits. Once this gets off the ground a bit more I'll ping you to make sure that we include all the information you need as we filter a lot of the noise out in the pipeline.

**Comment by decentralion** [comment]
@mikeal Sounds great :)

**Comment by wchargin** [comment]
@mikeal: Do you happen to know/suspect/recall whether querying just a
node’s `id` is helpful for priming the caches and making subsequent
queries more likely to succeed?

More concretely: if I want to find newly added comments on an issue,

```graphql
{
  node(id: "MDU6SXNzdWUzMjk2ODMxOTE=") {
    ... on Issue {
      comments(first: 10, after: "Y3Vyc29yOnYyOpHOF46x9Q==") {
        nodes {
          id
        }
      }
    }
  }
}
```

and get back two new comment IDs, then I can fetch the comments with

```graphql
{
  nodes(ids: [
    "MDEyOklzc3VlQ29tbWVudDM5NTY0MDI3Ng=="
    "MDEyOklzc3VlQ29tbWVudDQwODUwMjQ5MQ=="
  ]) {
    ... on Comment {
      id
      body
    }
  }
}
```

Alternately, I could have done this in one query:

```graphql
{
  node(id: "MDU6SXNzdWUzMjk2ODMxOTE=") {
    ... on Issue {
      comments(first: 10, after: "Y3Vyc29yOnYyOpHOF46x9Q==") {
        nodes {
          id
          body
        }
      }
    }
  }
}
```

…but this has some other disadvantages (primarily: large worst-case
result size; possibility of discovering a subtree multiple times in one
query).

The two-query version has the obvious disadvantage that it requires an
extra query, but it seems plausible to me that the first query could
prime the cache for the nodes in the second query, making up for or at
least mitigating the extra query cost. Any ideas?

**Comment by mikeal** [comment]
@wchargin I'm not entirely sure. We're basically trying to divine the database configuration and infrastructure we have little visibility into. I would start using it and see if it helps, the only tool we have here is trial and error :(

**Comment by wchargin** [comment]
@mikeal: Understood, thanks. I’ll post any interesting updates here. :-)

**Comment by wchargin** [comment]
This should be resolved. We retry on ephemeral failures. We cache the
state of the GitHub repository and pull in updates as needed (#622 has
merged!). We do autogenerate Flow types from a GraphQL schema. :heavy_check_mark:
