### ISSUE TITLE
Are edges nodes?

### ISSUE THREAD

**Issue by wchargin** [sourcecred/sourcecred#50]

**Comment by wchargin** [comment]
For context, here is a rough dump of the conversation that @dandelionmane and I had, leading to this issue.

If a `Node` has `address` and `payload`, and an `Edge` additionally has `src` and `dst`, then structurally `Edge` is an (inexact) subtype of `Node`. For instance, if your types are inexact, then Flow won’t complain if you try to use an edge as a node.

If we want to recognize that careful valuations are themselves valuable, then it kind of makes sense to be able to flow value to a valuation: i.e., have an edge to an edge.

If edges are nodes, then the types can be unified to something like
```js
export type Entity<T> = {|
  +address: Address,
  +payload: T,
  +hom: ?{| +src: Address, +dst: Address |},
|};
```
where the `src` and `dst` addresses are for any entity.

This also suggests that the address space should be unified, which is something that we had been wondering about previously.

If edges are nodes, then it’s not clear how standard graph algorithms work. But there is a “splicing” translation from ω-graphs (← good name for the “edges are nodes” data structure) to graphs, something like the following: if an edge `e : a → b` has an incident 2-edge `f : u → e`, then make a new node `•`, replace the edge `e` with edges `e_1 : a → •` and `e_2 : • → b`, and change the edge `f` to be `f : u → •`. It’s certainly not clear that the semantics of this translation are what we want, though—it’s not even clear what the semantics that we want _are_.

Using an ω-graph instead of a graph makes the resulting structure harder to understand at a glance.

**Comment by wchargin** [comment]
Note that the splicing transformation described above also yields useful semantics for hyperedges (edges with multiple sources or destinations), which is something else that we had considered and rejected.

**Comment by wchargin** [comment]
Also note that it is possible to have an unfounded structure with the type signature reprsented above. (I believe that it is not strictly an ω-graph, because its entities don’t admit meaningful ranks; I’ll call it an aleph-graph.) Using string addresses for simplicity:

```js
const entities = {
  "a": {
    address: "a", payload: {},
    hom: {src: "b", dst: "d"},
  },
  "b": {
    address: "b", payload: {},
    hom: {src: "a", dst: "c"},
  },
  "c": {
    address: "c", payload: {},
    hom: {src: "d", dst: "b"},
  },
  "d": {
    address: "d", payload: {},
    hom: {src: "c", dst: "a"},
  },
};
```

This aleph-graph has four entities, none of which is a node (0-entity). The structure could be drawn like this:

![Example drawing of an unfounded aleph-graph](https://user-images.githubusercontent.com/4317806/36939766-c6542e0e-1eeb-11e8-9788-235cd062650b.png)

The splicing transformation described above works inductively on rank, so is unable to transform this aleph-graph into a normal graph because there is no base case.

**Comment by dandelionmane** [comment]
Let's call "meta-valuation" the problem of assigning value to the work of assigning value. The motivation for making edges nodes is that it provides a seemingly principled solution to the meta-valuation problem. However, as @wchargin's discussion demonstrates, it also adds a lot of complexity to our underlying data structure. Also, when you look at the semantics closely, valuing edges rarely seems like the right thing to do. Most edges are programmatically generated by some tool, e.g. the GitHub plugin automatically generates edges that represent comment authorship or cross-reference. Rewarding the individual edge that effects cross-reference seems like a very indirect way to approach meta-valuation, since really we should be rewarding contributions to the tool that generated those edges.

In #41 I describe an "artifact" plugin that creates nodes that represent curated allocations of value to pieces and processes that compose a project. The each artifact has a meta-artifact which values the work of maintaining the artifact. I believe that artifacts and meta-artifacts make significant progress towards solving meta-valuation:

- For valuing auto-generated edges, the project itself should value artifact that auto-generates those edges. For example, if SourceCred values the GitHub value network, it should flow some Cred to the artifacts that maintain that network. (Precise semantics still need clarification).

My belief is that the artifact system, or followon developments, will allow us to solve the meta-valuation problem without needing to make every edge into a node. I think that even if we need to invent some clever abstractions or practices to make it all work, it will be better than taking on an significant complexity cost in our core data structure.

@wchargin if you find this persuasive, then let's close the issue
