### ISSUE TITLE
Test: ensure-flow-typing silently failing for Mac

### ISSUE THREAD

**Issue by claireandcode** [sourcecred/sourcecred#594]
The ensure-flow-typing test fails, but still is marked as a success within a local run of `yarn test`.
The issue seems twofold: 
* Incorrect syntax for grep within ensure-flow.sh (for a Mac)
* Error messages not being piped appropriately --> silent failure

**Comment by wchargin** [comment]
The script relies on GNU `grep`, which provides `-z`. POSIX `grep` is a
bit anemic in its supported options.

I’d be fine with documenting that GNU `grep` is a requirement. macOS
users can use `brew install grep --with-default-names` or something to
fix up their environments. From reading the BSD/macOS `grep` manual,
it’s not clear how we can implement the desired functionality safely
using the provided options.

If people are really against this, then I can probably rework the script
to use POSIX `awk` instead of GNU `grep`. :-) At a glance, it looks like

```shell
awk -v RS='\0' -v ORS='\0' '! /^flow-typed/'
```

should do it.

The silent failure can be fixed by adding `set -o pipefail` to the
script.

**Comment by wchargin** [comment]
Let me amend my position to: I am happy to rework the script to use
POSIX `awk`, but if scenarios like this come up in the future where
there isn’t such an easy change, then I would prefer requiring GNU grep
over choosing something like `tr '\0' '\n'`, which sacrifices safety.
