### ISSUE TITLE
Consider having edges refer to nodes rather than addresses

### ISSUE THREAD

**Issue by decentralion** [sourcecred/sourcecred#72]
Currently, the Edge type is as follows:

```ts
export type Edge<T> = {|
  +address: Address,
  +src: Address,
  +dst: Address,
  +payload: T,
|};
```

What if we changed it so that `src` and `dst` directly point point to `Node`s, as follows:

```ts
export type Edge<T> = {|
  +address: Address,
  +src: Node,
  +dst: Node,
  +payload: T,
|};
```

If callers actually want the src Address, they can just write `edge.src.address`, which is actually more explicit. And in the general case where you are running a graph algorithm, this approach is more efficient and useful.

Also, we could consider renaming `src` to `source` and `dst` to `target`, as this would be consistent with d3's [force layout api](https://github.com/d3/d3-force#link_links). However, I don't think this is a very important consideration, because the d3.forceSimulation API is already an imperfect fit for our Node and Edge data structures. (E.g. forceSimulation adds position properties, which we won't want in general.)

cc: @wchargin

**Comment by wchargin** [comment]
The major problem with this is that the resulting structure is no longer serializable.

A secondary problem is that `Graph.merge` with a nontrivial node resolver becomes much more expensive: for each resolution, you need to touch all edges, or at least all incident edges.

I'm totally fine with `source`/`target` instead of `src`/`dst`.

**Comment by wchargin** [comment]
What motivates this issue? Performance, usability, something else?

**Comment by dandelionmane** [comment]
I think it could present a benefit in terms of performance (fewer map lookups on graph traversal) and usability (makes a common case more convenient). However, you make a good point that it adds complexity to our algorithms. I suggest we table this, but set ourselves up with an easy path to add it in the future if we so desire. We can do this by renaming `Edge.src` and `Edge.dst` to `Edge.srcAddress` and `Edge.dstAddress`; more verbose, but more descriptive too. This way, if we decide down the line that it would be nice to give the objects direct pointers to the nodes as well, the naming will still be consistent.

Also, I think aligning with `d3-force` on layout is a non-goal, the abstractions are pretty different anyway, so let's forget about that.

**Comment by dandelionmane** [comment]
After giving some thought to https://github.com/sourcecred/sourcecred/issues/73, I now think that attempting to pre-load the `Node` is a bad idea, because in general the addressed nodes may be in a different value network, which is not locally accessible, or the lookup may be high-latency. So storing the Node cannot work in the general case.

I'm still weakly in favor of `srcAddress` and `dstAddress` because `explicit>implicit`.

**Comment by wchargin** [comment]
What's the difference?
