### ISSUE TITLE
Create a structured form for GraphQL queries

### ISSUE THREAD

**Issue by wchargin** [sourcecred/sourcecred#76]
We will need to be able to structurally manipulate GraphQL queries so
that we can implement general-purpose pagination against the GitHub API.
Amazingly, I wasn’t able to find such a library after some searching. In
particular, the official `graphql` npm package has structured schemata
(of course), but only stringly-typed queries, as far as I can tell.

Happily, GraphQL has a proper spec:
https://facebook.github.io/graphql/October2016/

This makes it easy to correctly define the relevant API. Our needs are
very simple: we just need an ADT for a GraphQL request (queries and
fragment definitions). The Flow-level types should express all the
complexity of the system, and there will be a projection function to
take a query to a GraphQL-formatted string. Some helper functions will
assist creation of the types for a fluent API, but this should basically
be it.

cc @dandelionmane

**Comment by dandelionmane** [comment]
This looks nice to me, although I don't fully understand the motivation behind it. I assume this gets us DRY-er code and, more importantly, a basis to handle pagination and retries in a principled fashion.

A few thoughts:

- Would it be an unreasonable metaprogramming ask to overload this structure so that it can both construct the appropriate graphQL query, and the flow type signature that the query will return? Then we could commit the generated typesignature in its own file, but have a test that verifies it is identical to what would be generated if we re-ran the generation function. It seems this could be accomplished by having your code be aware of the type expected for each field.

- Is this sufficiently generic that we should think about getting it adopted back into the reference implementation, or similar? (Maybe would consume a lot of rabbit hole budget.)

- We should factor all of the (first N) type arguments into constants, since we'll want to make those easy to tune.

**Comment by wchargin** [comment]
> (1)

It wouldn't be _unreasonable_ metaprogramming, in the sense that I could implement that in zero time I would absolutely do so. But I definitely think that it's out of the rabbit hole budget for right now. You say "having the code be aware of the type _expected_ for each field"—emphasis mine; I think we probably want something stronger than expectation. We should do something 

> (2)

Yes, I think so. The only major thing that I left out of the spec was directives, because we don't plan to use them, but they could be trivially added back in. I don't want to do this right now, though, not least because I want flexibility and control over the API. (There are already things that I want to change.)

> (3)

(I think that you are talking about our particular query for sourcecred rather than a generic API.) I am happy to consider doing that. Note that, now that we have a DSL, we can factor them into GraphQL query parameters or into JavaScript constants, as desired.

**Comment by dandelionmane** [comment]
Re (1) being out of the rabbit hole budget - do we expect to not have any typing at all for the result from running the query (status quo)? Or do we want to generate flow types for the query response and maintain it by hand (seems suboptimal since we could break things by changing the query) or via runtime type checking?

Given that we already have machinery for producing formatted strings (queries) from the structured query descriptor, it seems reasonable to also produce Flow type signatures. How about we use the fact that GraphQL schemas are introspective, and generate the typesig by talking to the actual prod server and getting the schema? Then, we can include verifying that the query types are correct with the non-CI test that verifies that the query works.

**Comment by wchargin** [comment]
> Re (1) being out of the rabbit hole budget - do we expect to not have any typing at all for the result from running the query (status quo)? Or do we want to generate flow types for the query response and maintain it by hand (seems suboptimal since we could break things by changing the query) or via runtime type checking?

I think that omitting types is fine for the short term. The queries have a small API surface area, so it should be easy enough to make sure that the (actual) types are kept in sync with any changes. In the long term, static typing would be great. I think that runtime checking would be superfluous, but maybe we could have it as an extra, optional check run (e.g.) only during tests.

> Given that we already have machinery for producing formatted strings (queries) from the structured query descriptor, it seems reasonable to also produce Flow type signatures.

The current mechanism is not type-aware. We could make it type-aware with a moderate amount of effort. We could then modify it to print Flow type signatures as strings, but I'm not aware of any way to actually integrate those type signatures into the rest of our code, so we'd have to build some tooling around it. All in all, it probably isn't conceptually hard, but I would expect it to take a few days to get right, and I'm just not convinced that it's worth it right now.

> How about we use the fact that GraphQL schemas are introspective, and generate the typesig by talking to the actual prod server and getting the schema? Then, we can include verifying that the query types are correct with the non-CI test that verifies that the query works.

Again, I agree that this is reasonable in principle but would take a couple days, and I'm not sure that it's the best use of time.

Per offline discussion, closing for now; we can reopen or keep discussing later.
