### ISSUE TITLE
Numeric reference detection breaks in multi-repo usecase

### ISSUE THREAD

**Issue by decentralion** [sourcecred/sourcecred#904]
Something I noticed incidentally, while investigating https://github.com/sourcecred/sourcecred/issues/903: when aggregating multiple repositories, we do not ensure that we link numeric references to the correct repository. 

Specifically: suppose we have repos `foo/a` and `foo/b`, both of which we merge together. Then suppose in repo `foo/a` we reference `#1`. We do not guarantee that the link will point to `foo/a/issues/1` rather than `foo/b/issues/1`. This is a bug.

**Comment by decentralion** [comment]
Relevant: https://github.com/sourcecred/sourcecred/issues/701

**Comment by wchargin** [comment]
To anyone interested in contributing to this issue: you’ll want to look
at `_addReferences` in `relationalView.js`:

<https://github.com/sourcecred/sourcecred/blob/23e56f481a72035197efb79be16566fb6afbcb47/src/plugins/github/relationalView.js#L468-L491>

Specifically, we create a map from “human-written string reference”
(like `"#123"`) to “unambiguous entity address” (like “pull request
`#123` in `sourcecred/sourcecred`”). The problem is that when multiple
repositories are in play, these human-written string references become
context-sensitive: issue number 123 in one repository is different from
an issue by the same number in another repository. The current behavior
is to choose an unspecified such entity.

One approach to a solution would be to instead map from human-written
references to a set of context-specific unambiguous entities, each with
an associated context in which it may be referenced. For instance, the
reference `"#123"` could map to
 
  - “if in the `sourcecred/sourcecred` repository: pull request `#123`
    in the `sourcecred/sourcecred` repository”; and _also_
  - “if in the `tensorflow/tensorflow` repository: issue `#123` in the
    `tensorflow/tensorflow` repository”.

When creating out-references from an entity, we’d then take its contexts
into account. 

Note that I say “contexts”. Most entities have a unique enclosing
context: the ancestor repository. But Git commits are also GitHub
entities, and can appear in many repositories. A reasonable behavior in
this case is that Git commits should create reference edges to _every_
repository in which they’re contained.

**Comment by decentralion** [comment]
This was fixed by https://github.com/sourcecred/sourcecred/pull/1248
